import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        type="module"
        src="https://unpkg.com/browse/three@0.153.0/examples/jsm/"
      ></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
